### ISSUE TITLE
How to simply rebind global keys like C-h

### ISSUE THREAD

**Issue by Compro-Prasad** [darkstego/rebinder.el#1]
Using the following doesn't help:

```
(define-key global-map (kbd "C-S-h") (rebinder-dynamic-binding "C-h"))
(define-key rebinder-mode-map (kbd "C-h") 'backward-char)
(rebinder-hook-to-mode 'prog-mode 'prog-mode-hook)
```

**Comment by darkstego** [comment]
rebinder works whenever a given mode is active, prog-mode itself is never really active, only modes derived from prog-mode, so the rebinder is never active.

If you want rebinder to work in all prog-modes then you must create your own minor-mode and enable it whenever a mode derived from prog-mode is active. 
`(add-hook 'prog-mode-hook 'my-minor-mode)`

If you want don't mind the rebind not being disabled when outside the prog-mode then you can a just set it to always on by changing the last line to the following.
`(rebinder-hook-to-mode 't 'after-change-major-mode-hook)
`

**Comment by Compro-Prasad** [comment]
That worked. Awesome!
